name: Main-Workflow

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  bump-dev-version: # only do that when actually merging in main/develop branch
    if: github.event_name != 'pull_request'
    uses: Felixmil/Workflows/.github/workflows/bump_dev_version_tag_branch.yaml@support-renv-in-main-wf
    with:
      app-id: ${{ vars.VERSION_BUMPER_APPID }}
    secrets:
      private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

  R-CMD-Check:
    if: ${{ !cancelled() }}
    needs: [bump-dev-version]
    uses: Felixmil/Workflows/.github/workflows/R-CMD-check-build.yaml@support-renv-in-main-wf

  test-coverage:
    if: ${{ !cancelled() }}
    needs: [bump-dev-version]
    uses: Felixmil/Workflows/.github/workflows/test-coverage.yaml@support-renv-in-main-wf
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pkgdown:
    if: ${{ !cancelled() }}
    needs: [bump-dev-version]
    uses: Felixmil/Workflows/.github/workflows/pkgdown.yaml@support-renv-in-main-wf
